services:
  sendyxmail:
    build:
      context:  ../../
      dockerfile: docker/Dockerfile
      no_cache: true
      pull: true
      tags:
      - "filimonic/sendyxmail:latest"
      - "filimonic/sendyxmail:v0.0.1"
    image: filimonic/sendyxmail:latest
    container_name: sendyxmail
    ports:
      - "8000:8000"
    env_file:
      - path: sendyxmail.env
        required: true
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    volumes:
      - target: /run/secrets/tokens
        source: ./tokens.yml
        type: bind
        read_only: true
      - target: /mutes
        source: ./mutes
        type: bind
        bind:
          create_host_path: true
        read_only: false
      - target: /certs
        source: ./certs
        type: bind
        read_only: true
        bind:
          create_host_path: true
    environment:
      TOKEN_FILE: /run/secrets/tokens
      MUTE_FILE: /mutes/mutes.txt
    ulimits: &ulimits
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000